api/src/db.js, api/src/models/Comment.js, api/src/models/Genre.js, api/src/models/User.js, api/src/models/Videogame.js
Cree la base de datos con sus respectivos modelos en el back end.
=> Base de datos con modelos

client/src/components/Cards/Card.jsx, client/src/components/Cards/Cards.jsx
Agrego carpetas y parte del codigo, necesito pullear el hardcodeo del back
=> newFeature_Card_Cards

client/src/App.css, client/src/App.js, client/src/Routes.js, client/src/components/Pagination/Pagination.jsx
creo componente paginado con datos hardcodeados
=> Pagination component created

client/src/components/Filters/SelectPrice.jsx, client/src/components/Filters/SelectRating.jsx, client/src/components/Filters/SelectType.jsx, client/src/sections/Home.jsx
Renderizado de filtros por rating, precio y tipo
=> filtros cambios

client/src/components/Cards/Card.jsx, client/src/components/Navbar/Navbar.jsx, client/src/components/Wishes/AddtoWishes.jsx, client/src/redux/reducers/videoGame.js
se agrega icono condicional para agregar a la lista de deseos
=> Feature addtowishes

client/src/components/Filters/SelectPrice.jsx, client/src/components/Filters/SelectRating.jsx, client/src/components/Filters/SelectType.jsx, client/src/redux/actions/videoGame.js
-Creación ordenamiento alfabetico
-Agregado de estrellas al filtro rating
-Agregado de rango al filtro precio
=> actualización filtros

client/src/components/Filters/SelectGenere.jsx, client/src/redux/actions/videoGame.js
=> filtro genre ya funcional

client/src/components/Filters/SelectGenere.jsx, client/src/components/Filters/SelectPrice.jsx, client/src/components/Filters/SelectRating.jsx, client/src/components/Filters/SelectType.jsx, client/src/redux/actions/videoGame.js
Agregue un seteo de current page a los filtros
=> filtros casi listos

client/src/Routes.js, client/src/components/ErrorNotFound/DisableElevation.css, client/src/components/ErrorNotFound/DisableElevation.jsx, client/src/components/ErrorNotFound/ErrorNotFound.jsx, client/src/pages/NotFound.jsx
-Creacion de componente error
-Creacion de boton para regresar al home (provisionalmente "/")
-Agregado de componente error a rutas inexistentes
=> Creacion componente error

client/src/sections/Games.jsx
-Agregado de mensaje de resultado inexistente en home main (busqueda y filtrado)
=> renderizado mensaje busqueda inexistente

client/src/components/ErrorNotFound/DisableElevation.jsx, client/src/pages/Detail.jsx
Importacion de boton DisableElevation (boton de regresar al home) en el detail de la card
=> agregado de boton regresar en detail

client/src/components/Filters/CleanButton.jsx, client/src/redux/actions/videoGame.js, client/src/redux/reducers/videoGame.js, client/src/sections/Filter.jsx
Creacion de boton limpiar filtros
Nueva accion añadida al reducer
=> Boton para limpiar filtros

client/src/redux/actions/videoGame.js
=> filtro precios

client/package-lock.json, client/package.json, client/src/pages/Detail.jsx
Para modificar las etiquetas que se traian del back a la seccion de Detail
=> FixHtmlToReact

client/src/Routes.js, client/src/components/Navbar/Navbar.jsx, client/src/components/Purchases/Purchases.jsx, client/src/redux/actions/user.js, client/src/redux/reducers/user.js
creacion nueva ruta purchases
creacion componente purchases
creacion estado global purchases
=> Creacion historial compras

client/src/Routes.js, client/src/components/Sidebar/Sidebar.jsx
creacion de tura de biblioteca de juegos
=> creacion ruta my colection

api/src/controllers/videogameControllers.js, api/src/db.js, api/src/models/PurchaseOrder.js, api/src/models/Videogame.js
=> Leandro martino

client/src/Routes.js, client/src/components/Collection/Collection.jsx, client/src/redux/actions/user.js, client/src/redux/reducers/user.js
nuevo estado global en user
nuevo componente
=> creacion de estado global y componente

api/src/controllers/paymentController.js, client/src/App.js, client/src/components/PaymentForm/PaymentForm.jsx, client/src/components/Review/Review.jsx, client/src/index.js, client/src/pages/Cart.jsx
=> Co-authored-by: Federico Goldammer <Zaikkoz@users.noreply.github.com>

api/src/controllers/Orders.js, api/src/routes/index.js
id required by params
status required by body
=> ChangePurchaseOrder status

api/src/controllers/Orders.js, api/src/routes/index.js
get user orders id required by params
create order error managment
=> get user orders id required by params

client/src/components/AdminNavBar/index.jsx
Se cambio el componente Link por el Link de Materia con las misma propiedades del Link de de React Dom
=> Se cambio el componente Link

client/src/components/EditForm/BotonEditar.jsx, client/src/components/EditForm/EditForm.jsx, client/src/pages/Detail.jsx
Creacion de boton que despliega formulario edit
Renderizado de boton en detail
=> renderizado de boton edit en detail

client/src/components/EditForm/EditForm.jsx, client/src/redux/actions/videoGame.js, client/src/redux/reducers/videoGame.js
Nuevo estado globla de negeros
nueva action para traer todos los generos para el select del form
=> nuevo estado global para generos

client/src/components/Sidebar/Sidebar.jsx
=> Bug Solucionado de Dark Mode

client/src/components/EditForm/EditForm.jsx, client/src/redux/actions/videoGame.js, client/src/redux/reducers/videoGame.js
=> nueva action post

client/src/components/Cards/Card.jsx, client/src/components/Cards/Cards.css
Agregandole un poco mas de diseño a las cards de juegos
=> CardsDesign

client/src/components/Cards/Card.jsx, client/src/components/Cards/Cards.css, client/src/components/Filters/CleanButton.jsx, client/src/components/Filters/SelectGenere.jsx, client/src/components/Filters/SelectPrice.jsx, client/src/components/Filters/SelectRating.jsx, client/src/components/Filters/SelectType.jsx, client/src/components/Filters/filter.css, client/src/components/Filters/filtro.jsx, client/src/components/Nosotros/Nosotros.jsx, client/src/pages/Detail.css, client/src/pages/Detail.jsx, client/src/sections/Filter.jsx, client/src/sections/Games.jsx
Nuevos estilos y hacer que sección de filtros no baje al hacer scroll
=> FilterComponentNewStyles

client/src/components/CreateForm/BotonCrear.jsx, client/src/components/CreateForm/CreateForm.jsx, client/src/pages/AdminGames.jsx
boton añadido a panel de admin
=> creacion de juegos funcional

client/src/components/ContactUsComponent/ContactUs.jsx, client/src/components/ContactUsComponent/validations.js, client/src/components/LandingForm/validations.js
Existia un conflicto con el validado del formulario y el del login.
Ahora cada uno tiene su validación
=> Solve Conflicto

client/src/components/Nosotros/Nosotros.jsx
=> card about

api/index.js, api/package-lock.json, api/package.json, api/src/app.js, api/src/db.js
Reverts LeandroLagreca/proyecto-final#292
=> Revert "deploy app"

client/src/App.js, client/src/components/Cards/Card.jsx, client/src/components/Filters/CleanButton.jsx, client/src/components/Filters/SelectGenere.jsx, client/src/components/Filters/SelectPrice.jsx, client/src/components/Filters/SelectRating.jsx, client/src/components/Filters/SelectType.jsx, client/src/components/Filters/filter.css, client/src/components/Filters/filtro.jsx, client/src/components/LandingForm/index.jsx, client/src/components/Loader/Loader.jsx, client/src/index.js, client/src/pages/MainHome.jsx, client/src/sections/Filter.jsx, client/src/sections/Games.jsx, client/src/sections/LandingFormSection.jsx
styles log in and filter section
=> Feature styles login

api/src/controllers/videogameControllers.js, client/src/components/EditForm/EditForm.jsx, client/src/redux/actions/videoGame.js, client/src/redux/reducers/videoGame.js
formulario de edicion funcional
=> Form edit juegos hecho
